version: '3'
services:
  db:
    environment:
      POSTGRES_DB: chess_ladder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    image: postgres
    ports:
      - 5432:5432
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: 'chess_ladder'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    links:
      - db
      - front

  front:
    build:
      context: /home/stoker/dev/vueladder
      dockerfile: frontend.dockerfile
    ports:
      - "8080:8080"

